-- Create sync_requests table for manual sync functionality
CREATE TABLE public.sync_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sync_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  requested_at timestamp with time zone DEFAULT now() NOT NULL,
  requested_by text DEFAULT 'dashboard',
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  result text,
  error_message text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT sync_requests_pkey PRIMARY KEY (id)
);

-- Add indexes for better performance
CREATE INDEX idx_sync_requests_status ON public.sync_requests(status);
CREATE INDEX idx_sync_requests_requested_at ON public.sync_requests(requested_at);

-- Add RLS (Row Level Security) policies
ALTER TABLE public.sync_requests ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read sync requests
CREATE POLICY "Allow authenticated users to read sync requests" ON public.sync_requests
  FOR SELECT USING (auth.role() = 'authenticated');

-- Allow authenticated users to insert sync requests
CREATE POLICY "Allow authenticated users to insert sync requests" ON public.sync_requests
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Allow service role to update sync requests (for office script)
CREATE POLICY "Allow service role to update sync requests" ON public.sync_requests
  FOR UPDATE USING (auth.role() = 'service_role');




